### ISSUE TITLE
        TensorflowProvider tfp = new TensorflowProvider(

### ISSUE THREAD

**Issue by yuanjie-ai** [handong0123/tensorflow_serving#2]
/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/lib/tools.jar:/Users/yuanjie/Desktop/Projects/Java/tql-Java/target/classes:/Users/yuanjie/.m2/repository/org/slf4j/slf4j-nop/1.7.2/slf4j-nop-1.7.2.jar:/Users/yuanjie/.m2/repository/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar:/Users/yuanjie/.m2/repository/com/github/handong0123/tensorflow-deploy-cpu/1.14.0/tensorflow-deploy-cpu-1.14.0.jar:/Users/yuanjie/.m2/repository/org/tensorflow/tensorflow/1.14.0/tensorflow-1.14.0.jar:/Users/yuanjie/.m2/repository/org/tensorflow/libtensorflow_jni/1.14.0/libtensorflow_jni-1.14.0.jar:/Users/yuanjie/.m2/repository/org/tensorflow/libtensorflow/1.14.0/libtensorflow-1.14.0.jar:/Users/yuanjie/.m2/repository/org/tensorflow/proto/1.14.0/proto-1.14.0.jar:/Users/yuanjie/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar:/Users/yuanjie/.m2/repository/org/springframework/boot/spring-boot/1.4.0.RELEASE/spring-boot-1.4.0.RELEASE.jar:/Users/yuanjie/.m2/repository/org/springframework/spring-core/4.3.2.RELEASE/spring-core-4.3.2.RELEASE.jar:/Users/yuanjie/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/yuanjie/.m2/repository/org/springframework/spring-context/4.3.2.RELEASE/spring-context-4.3.2.RELEASE.jar:/Users/yuanjie/.m2/repository/org/springframework/spring-aop/4.3.2.RELEASE/spring-aop-4.3.2.RELEASE.jar:/Users/yuanjie/.m2/repository/org/springframework/spring-beans/4.3.2.RELEASE/spring-beans-4.3.2.RELEASE.jar:/Users/yuanjie/.m2/repository/org/springframework/spring-expression/4.3.2.RELEASE/spring-expression-4.3.2.RELEASE.jar:/Users/yuanjie/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar:/Users/yuanjie/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/yuanjie/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/yuanjie/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/yuanjie/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar:/Users/yuanjie/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar:/Users/yuanjie/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/yuanjie/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/yuanjie/.m2/repository/com/alibaba/fastjson/1.2.62/fastjson-1.2.62.jar:/Users/yuanjie/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar:/Users/yuanjie/.m2/repository/org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar:/Users/yuanjie/.m2/repository/net/sourceforge/javacsv/javacsv/2.0/javacsv-2.0.jar:/Users/yuanjie/.m2/repository/com/sparkjava/spark-core/2.7.2/spark-core-2.7.2.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-server/9.4.8.v20171121/jetty-server-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-http/9.4.8.v20171121/jetty-http-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-util/9.4.8.v20171121/jetty-util-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-io/9.4.8.v20171121/jetty-io-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-webapp/9.4.8.v20171121/jetty-webapp-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-xml/9.4.8.v20171121/jetty-xml-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.8.v20171121/jetty-servlet-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-security/9.4.8.v20171121/jetty-security-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/websocket/websocket-server/9.4.8.v20171121/websocket-server-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/websocket/websocket-common/9.4.8.v20171121/websocket-common-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/websocket/websocket-client/9.4.8.v20171121/websocket-client-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/jetty-client/9.4.8.v20171121/jetty-client-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/websocket/websocket-servlet/9.4.8.v20171121/websocket-servlet-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/org/eclipse/jetty/websocket/websocket-api/9.4.8.v20171121/websocket-api-9.4.8.v20171121.jar:/Users/yuanjie/.m2/repository/com/hankcs/hanlp/portable-1.7.3/hanlp-portable-1.7.3.jar:/Users/yuanjie/.m2/repository/com/xiaomi/minlp/minlp-tokenizer-tf/2.0-SNAPSHOT/minlp-tokenizer-tf-2.0-20190622.085934-6.jar:/Users/yuanjie/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/yuanjie/.m2/repository/com/xiaomi/minlp/minlp-tokenizer-core/2.0-SNAPSHOT/minlp-tokenizer-core-2.0-20190622.085931-7.jar:/Users/yuanjie/.m2/repository/org/ahocorasick/ahocorasick/0.4.0/ahocorasick-0.4.0.jar:/Users/yuanjie/.m2/repository/com/xiaomi/minlp/minlp-intervener/2.0-SNAPSHOT/minlp-intervener-2.0-20190621.061605-2.jar:/Users/yuanjie/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/Users/yuanjie/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar:/Users/yuanjie/.m2/repository/org/jetbrains/annotations/19.0.0/annotations-19.0.0.jar:/Users/yuanjie/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/yuanjie/.m2/repository/com/squareup/okhttp3/okhttp/3.14.2/okhttp-3.14.2.jar:/Users/yuanjie/.m2/repository/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar:/Users/yuanjie/.m2/repository/org/jsoup/jsoup/1.10.3/jsoup-1.10.3.jar:/Users/yuanjie/.m2/repository/javax/xml/jaxp-api/1.4.2/jaxp-api-1.4.2.jar:/Users/yuanjie/.m2/repository/net/sourceforge/htmlcleaner/htmlcleaner/2.9/htmlcleaner-2.9.jar:/Users/yuanjie/.m2/repository/org/jdom/jdom2/2.0.5/jdom2-2.0.5.jar:/Users/yuanjie/.m2/repository/com/google/collections/google-collections/1.0/google-collections-1.0.jar deploy.TF
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/85/q9w9bf8n251440hct1lb63vc0000gn/T/tensorflow_native_libraries-1584091676965-0/libtensorflow_jni.dylib: dlopen(/private/var/folders/85/q9w9bf8n251440hct1lb63vc0000gn/T/tensorflow_native_libraries-1584091676965-0/libtensorflow_jni.dylib, 1): Library not loaded: @rpath/libtensorflow_framework.1.dylib
  Referenced from: /private/var/folders/85/q9w9bf8n251440hct1lb63vc0000gn/T/tensorflow_native_libraries-1584091676965-0/libtensorflow_jni.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:101)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:66)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)
	at org.tensorflow.Graph.<clinit>(Graph.java:479)
	at com.github.handong0123.tensorflow.deploy.session.model.TensorflowModelServiceImpl.init(TensorflowModelServiceImpl.java:66)
	at com.github.handong0123.tensorflow.deploy.session.model.TensorflowModelServiceImpl.<init>(TensorflowModelServiceImpl.java:57)
	at com.github.handong0123.tensorflow.deploy.session.model.TensorflowModelServiceImpl.<init>(TensorflowModelServiceImpl.java:48)
	at com.github.handong0123.tensorflow.deploy.provider.TensorflowProvider.<init>(TensorflowProvider.java:72)
	at com.github.handong0123.tensorflow.deploy.provider.TensorflowProvider.<init>(TensorflowProvider.java:47)
	at com.github.handong0123.tensorflow.deploy.provider.TensorflowProvider.<init>(TensorflowProvider.java:38)
	at deploy.TF.main(TF.java:17)

Process finished with exit code 1

**Comment by handong0123** [comment]
解决方案参照我的博客 https://blog.csdn.net/handong01027/article/details/101371739
